### ISSUE TITLE
Build failed due to 'Metadata version mismatch' in 11.0.0

### ISSUE THREAD

**Issue by vincent-cm** [swimlane/ngx-datatable#1105]
AoT build failed Error: Metadata version mismatch for module ~/node_modules/@swimlane/ngx-datatable/release/datatable.module.d.ts, found version 4, expected 3

**I'm submitting a BUG**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Error: Metadata version mismatch for module ~/node_modules/@swimlane/ngx-datatable/release/datatable.module.d.ts, found version 4, expected 3

after upgrade 11.0.0 
**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

npm build to AoT
**Please tell us about your environment:**

macOS 12.13.1 npm 
* **Table version:** 0.8.x

* **Angular version:** 2.0.x

4.6.6
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by nitinht1988** [comment]
Version 11.0.0 is only for Angular 5. If you are using older angular version please downgrade your ngx-datatable to 10.x

**Comment by mdentinho** [comment]
@nitinht1988 I'm having the same issue with version `10.5.0` and Angular `4.4.6`.

**Comment by pranavsreedhar92** [comment]
Having same issue but failed to compile
version: 10.0.0
node : v6.10.0
npm  :  v3.10.10

**Comment by pr0menade** [comment]
The same issue: **ERROR in Metadata version mismatch for module .../node_modules/@swimlane/ngx-datatable/release/index.d.ts, found version 4, expected 3,**
version: 10.0.5
Angular: 4.3.5
cli: 1.3.0
node: v7.7.3
npm: 4.1.2

**Comment by Neuropatic** [comment]
I have the same problem and i've not yet solved it. I cant continue my job cause of this problem....waiting for help.

ERROR in Metadata version mismatch for module
node_modules/@swimlane/ngx-datatable/release/index.d.ts, found version 4, expected 3

**Comment by mdentinho** [comment]
Just to give few more information:
- The issue's title says AoT, but I'm having this issue without it.
- It happens on `serve`, `test` and `build`
- Even though it doesn't block the work, it does block deployment since the `build` returns an error.

**Comment by Paul75** [comment]
Hello,

same error with the version 10.5.0 and Angular 4.4.6....

If i downgrade with the version 9.3.1 it works....

Thanks

**Comment by ramauidev** [comment]
Hello,

The same error just downgraded the Datatable version to 10.4.0 and it works :)

Thanks

**Comment by Paul75** [comment]
For me only the 9.3.0 works 

⁣Envoyé par TypeApp ​

Le 7 nov. 2017 à 18:16, à 18:16, ramauidev <notifications@github.com> a écrit:

**Comment by Paul75** [comment]
for me I have this error :
`ERROR in Error: Metadata version mismatch for module /node_modules/@swimlane/ngx-datatable/release/index.d.ts, found version 4, expected 3, resolving symbol HomeModule in /src/app/+home/home.module.ts, resolving symbol HomeModule in /src/app/+home/home.module.ts`

in 9.3.0 not do this ....

Thanks

**Comment by amcdnl** [comment]
Can someone make a demo project showing this?

**Comment by ingarpo** [comment]
Hello everyone, same Error
I fixed it updating to "@swimlane/ngx-datatable": "^10.4.0"

In dependenies all @angular 4.4.6
In devDependencies: 
 "@angular/cli": "^1.5.0",
    "@angular/compiler-cli": "^4.4.6",
    "@angular/language-service": "^4.4.6"

I hope this helps somebody

**Comment by amcdnl** [comment]
Looks like Material is having this issue too - https://github.com/angular/material2/issues/8229#issuecomment-342502556

**Comment by szanellato93** [comment]
Same error here. I updated ngx datatable to version 11 and all angular dependencies to angular 5. I received some errors.. after the downgrade i received this new error. Please help.

**Comment by knehez** [comment]
Same error here. but fixed with "@swimlane/ngx-datatable": "10.4.0"  
I removed "^" before 10.4.0

**Comment by ShinDarth** [comment]
I can confirm the issue, using Angular 4. And I can also confirm that the solution posted by @knehez works.
So my guess is that there is something wrong with version `10.5.0`.

**Comment by amcdnl** [comment]
Is this still an issue in 11.0.4??

**Comment by Farre82** [comment]
Hi,
"@angular/core": "5.0.2" and  "@swimlane/ngx-datatable": "11.1.2",  still gives 
**ERROR in Metadata version mismatch for module .../node_modules/@swimlane/ngx-datatable/release/index.d.ts, found version 4, expected 3,**

**Comment by nadysaptra** [comment]
@amcdnl it was still an issue
i was having the same problem
@swimlane/ngx-datatable@10.5.0
@angular @4.4.6

**Comment by diegosilva13** [comment]
> Same error here. but fixed with "@swimlane/ngx-datatable": "10.4.0"
I removed "^" before 10.4.0
Thanks @knehez , It's working for us.

**Comment by Hypercubed** [comment]
Please reopen if this is still an issue.
